version: "3"

services:
  ground-station:
    build: .
    tty: true
    privileged: true
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./px4_ros_com_ros2:/root/px4_ros_com_ros2
      - ./super_client_configuration_file.xml:/root/super_client_configuration_file.xml
    environment:
      - DISPLAY=$DISPLAY
      - FASTRTPS_DEFAULT_PROFILES_FILE=/root/super_client_configuration_file.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=192.168.1.150:11811
